services:
  - type: web
    name: aerilux-website
    runtime: static
    rootDir: .
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 22.14.0

